### DISCUSSION TITLE
Help with footer taking up too much space when less content above

### DISCUSSION THREAD

**Discussion by gurds91** [holger1411/understrap#1802] [Q&A] [answered]
Hi,

I am having an issue. On this particular page ,I have less content, is just one testimonial alert in the "wrapper bg-primary" div class.

I didn't want to use wordpress loop for this page so I removed the loop and echoed out title using <?php $title = get_the_title();

               echo "<h1>$title</h1>";  ?> 

My issue is  , it seems as we are using the get_footer() function to get the footer after the full width page wrapper ends. If this wrapper is short due to not much info then the footer gets pushed up a lot. 

If you wanted to have a different background colour for the footer then that would look awful as well as then a massive chunk of page where footer is would be different colour.

Pls help
![Issue with footer](https://user-images.githubusercontent.com/107938466/176920927-2a28dd17-a91f-4cfb-b14f-3a99d640ff57.png)
![portfolio page look](https://user-images.githubusercontent.com/107938466/176921221-4b95543f-82d6-4a16-9a3d-824456e34973.jpg)

**Comment by IanDelMar** [comment, marked as answer]
The footer is not taking up to much space but simply follows directly after the content which is too short to fill the page. If you want the footer to stick to the bottom on pages with less content without having a fixed footer try something like this:

```scss
html {
  height: 100%;
}

body {
  position: relative;
  min-height: 100%;
}

#wrapper-footer {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
}
```
