### DISCUSSION TITLE
Help with adding hover effect to navbar

### DISCUSSION THREAD

**Discussion by gurds91** [holger1411/understrap#1804] [Q&A] [answered]
Hi, I wanted some help adding a hover effect to the navbar.

I wanted a blue circle around the links in navbar when hovering over them (light blue colour same as primary light blue colour below navbar). 

Also wanted to create spacing between the links in the navbar. 

At the moment the navbar is dynamic as it uses the bootstrap navwalker to make it dynamic, 
navigation is bootstrap 5 off canvas. 

![navbar bootstrap 5](https://user-images.githubusercontent.com/107938466/177038334-841e417e-cfb4-4b52-9bd0-ee83846aa150.jpg)

**Comment by IanDelMar** [comment, marked as answer]
Here's a starting point:
```scss
@include media-breakpoint-up(lg) { // use the breakpoint at which the navbar gets expanded
  .nav-link:hover {
    border: $border-width $border-style $border-color;
    border-radius: $border-radius;
    // replace the variables with the width, style, color and radius you would like to have
  } 
  .nav-item {
    padding-left: .5rem; 
    padding-right: .5rem;
    // replace with the desired padding
    &:last-child {
      padding-right: 0;
    }
  }
}
```
