### DISCUSSION TITLE
How to place footer at the bottom of the page?

### DISCUSSION THREAD

**Discussion by Brillios** [holger1411/understrap#2186] [Q&A] [answered]
I've recently tried to create a custom theme from scratch. I know docs suggest going with a child theme but I went directly with the parent one. Anyway I didnt change much yet so basically the theme looks almost the same.  

So the question is how to make my footer be on the bottom of the page? I dont want it to be sticky but to have basically set `footer margin:auto`.

This is how it currently looks:
![image](https://github.com/understrap/understrap/assets/37155232/8f73abb6-5dc3-4980-b1b2-35f06a37d2b1)

I looked around and I found similar suggestions [here](https://stackoverflow.com/questions/62796071/bootstrap-footer-doesnt-stick-to-the-bottom-of-the-page). Problem is it doesnt work and I guess its something from the themes configs/styling that is preventing me.

Any ideas?

**Comment by IanDelMar** [comment, marked as answer]
```scss
.site {
	display: flex;
	flex-direction: column;
	min-height: 100vh;
}

#single-wrapper {
	flex-grow: 1;
}
```
