### ISSUE TITLE
searchform.php doesn't seem to override the new gutenberg-based search widget

### ISSUE THREAD

**Issue by bacoords** [holger1411/understrap#1533]
The search widget that shows up now as a block instead of the old widget doesn't get the correct button/input styling

**Comment by bacoords** [comment]
This one solution we've had internally, though i'm going to see if we can use more mixins instead of `@include` for some of these before starting a PR:

```scss

/* Search Widget */
.wp-block-search {
    .wp-block-search__label {
        @extend .screen-reader-text;
    }

    .wp-block-search__inside-wrapper {
        @extend .input-group;

        .wp-block-search__input {
            @extend .form-control;
        }

        .wp-block-search__button {
            border-radius: $border-radius;

            &:not(:first-child):not(.dropdown-menu):not(.valid-tooltip):not(.valid-feedback):not(.invalid-tooltip):not(.invalid-feedback) {
                margin-left: 0;
            }            

            @extend .btn-primary;
        }
    }
}
```
