### ISSUE TITLE
How to use SCSS - Npm - Gulp

### ISSUE THREAD

**Issue by stef-k** [holger1411/understrap#158]
@holger1411 i've made a small how to guide not sure where should be here on README or in documentation page, can you put it somewhere?

# How to develop with SCSS - NPM - Gulp

This little how to is for Linux - OS X users how currently know how to clone the
project from Github. If not check this tutorial here http://product.hubspot.com/blog/git-and-github-tutorial-for-beginners

Assumptions: you have cloned project's source and you want to start styling various
parts of the theme. Additionally you have Node.js installed on your system, if not check here how to do it https://nodejs.org/en/download/package-manager/

1. Go to project's root directory

1. Install project's toolchain and dependencies using `npm install`. When this command completes, you should be able to see a new directory named `node_modules` under project's root directory (`understrap/node_modules`)

1. Move various needed libraries from `node_modules` where installed with `npm install` to project's root directory by typing `gulp copy-assets`. When this command complete, you should be able to see a new directory named `src` under project's root directory (`understrap/src`).

We the above prerequisites complete, you are now ready to start developing - styling your copy of Understrap.
For this guide, we will do the following:

- create a SCSS variable
- see how to nest style rules
- use the variable to change navbar's link colors
- see how to reference parent selector while nesting rules to handle a hover event

## Running the watcher

First we must run the watcher process which is responsible to track file changes and compile these changes to the final CSS file which in turn WordPress loads.
From the terminal and while in project root directory type `gulp watch`. You should see something like the following:
```shell
stef@dev:understrap$ gulp watch
[13:06:47] Using gulpfile ~/projects/php/wordpress/wp-content/themes/understrap/gulpfile.js
[13:06:47] Starting 'watch'...
[13:06:47] Finished 'watch' after 12 ms
```

leave the terminal open with the command running as is.

## Styling the theme

With the watcher running, open the SCSS file `understrap/sass/theme/_theme.scss` and paste the following,
(**you should also read the comments**):

```scss
// SCSS Syntax http://sass-lang.com/documentation/file.SASS_REFERENCE.html#css_extensions

// variable declaration in SCSS we use variables to keep style clean and easy to modify
// if we use this variable to say 50 rules and want to change the color, we would change only this variable.
$mycolor: #67A6A6;

// in SCSS we nest
nav {
  // in CSS this was selected by nav a
  a {
    color: $mycolor !important;
    // change a on hover example
    // n CSS this was selected by nav a:hover
    &:hover {
      color: $brand-primary !important;
    }
  }
}
```

by saving the file you should see in terminal something like the following:

```shell
[13:15:22] Starting 'sass'...
[13:15:22] Finished 'sass' after 1.36 ms
[13:15:22] Starting 'cleancss'...
[13:15:22] Finished 'cleancss' after 2.81 ms
[13:15:22] Starting 'cssnano'...
[13:15:23] Finished 'cssnano' after 737 ms
```

reload the page and you should be able to see the new style applied.

## Continuing from here

By now you should be able to style the theme addordingly but before that,
check about Browser Sync https://github.com/holger1411/understrap#developing-with-npm-gulp-and-sass-and-browser-sync1 to learn how to auto refresh your browser while changing the source code.
